ht: ht.h File Reference
ht.h File Reference
#include <stdlib.h>
Classes
struct hte
hash table entry.
union hte::key
union hte::val
struct ht
Macros
#define hte_create(key, value)
#define ht_search(ht, key)
Typedefs
typedef struct hte hte
hash table entry.
typedef struct ht ht
Enumerations
enum key_type { INT_KEY, CHARP_KEY }
key value types
enum val_type { INT_VAL, FLT_VAL, CHARP_VAL, VOIDP_VAL }
Functions
hte hte_create_int_int_entry (int key, int val)
hte hte_create_int_flt_entry (int key, float val)
hte hte_create_int_charp_entry (int key, char *val)
hte hte_create_int_voidp_entry (int key, void *val)
hte hte_create_charp_int_entry (char *key, int val)
hte hte_create_charp_flt_entry (char *key, float val)
hte hte_create_charp_charp_entry (char *key, char *val)
hte hte_create_charp_voidp_entry (char *key, void *val)
hte * ht_search_i (ht h, int key)
hte * ht_search_str (ht h, char *key)
ht ht_alloc (size_t size, unsigned int key_type, unsigned int val_type)
create a new hash table with a set size and key val scheme.
ht ht_alloc_dynamic (size_t size, unsigned int key_type, unsigned int val_type)
create a new hash table with a dynamic size and key val scheme.
int ht_free (ht *h)
frees a hash tables internal table.
int ht_is_full (ht h)
check if hash table is full.
int ht_is_empty (ht h)
check if hash table is empty
int ht_typematch (ht h, hte e)
check that a table and entry have the same key val scheme.
int ht_add (ht *h, hte e)
add an entry to a hash table.
int ht_shrink (ht *h)
shrink container to remove wasted space.
void ht_print (ht h)
print out a hash tables data.
void hte_print (hte e)
print out a single hash table entry.
void hte_print_chain (hte e)
Macro Definition Documentation
ht_search
#define ht_search (ht, key)
Value:
  _Generic ((key), \
  int : ht_search_i, char* : ht_search_str \
) (ht, key)
Definition at line 79 of file ht.h.
hte_create
#define hte_create (key, value)
Value:
  _Generic ((key), \
  int:   _Generic ((value), \
    int:   hte_create_int_int_entry,   \
    float: hte_create_int_flt_entry,   \
    char*: hte_create_int_charp_entry, \
    void*: hte_create_int_voidp_entry \
  ),\
  char*: _Generic((value), \
    int:   hte_create_charp_int_entry,   \
    float: hte_create_charp_flt_entry,   \
    char*: hte_create_charp_charp_entry, \
    void*: hte_create_charp_voidp_entry \
  )) (key, value)
Definition at line 63 of file ht.h.
Typedef Documentation
ht
typedef struct ht ht
hte
typedef struct hte hte
hash table entry.
stores a single entry of a hash table, containing type information, key, value, and a ptr to the next entry of this key
Enumeration Type Documentation
key_type
enum key_type
key value types
Enumerator
INT_KEY
CHARP_KEY
Definition at line 11 of file ht.h.
val_type
enum val_type
Enumerator
INT_VAL
FLT_VAL
CHARP_VAL
VOIDP_VAL
Definition at line 16 of file ht.h.
Function Documentation
ht_add()
int ht_add (ht * h, hte e)
add an entry to a hash table.
will auto expand if hash table has .dynamic.
Parameters
h hash table ptr
e hash table entry
Returns
an exit code
Definition at line 317 of file ht.c.
References ht::capacity, ht::dynamic, ht_is_full(), ht_search_i(), ht_search_str(), ht_typematch(), hte::key::i, INT_KEY, hte::key, hte::key_type, ht::len, hte::next, hte::key::s, and ht::table.
ht_alloc()
ht ht_alloc (size_t size, unsigned int key_type, unsigned int val_type)
create a new hash table with a set size and key val scheme.
Parameters
size the initial size for the hash table
key_type enum for type of key
val_type enum for type of val
Returns
ht<key, val>
Definition at line 89 of file ht.c.
References ht::capacity, ht::key_type, ht::table, and ht::val_type.
ht_alloc_dynamic()
ht ht_alloc_dynamic (size_t size, unsigned int key_type, unsigned int val_type)
create a new hash table with a dynamic size and key val scheme.
all contents passed to regular ht_alloc, then dynamic flag is set.
Parameters
size the initial size for the hash table
key_type enum for type of key
val_type enum for type of val
Returns
ht<key, val>
Definition at line 112 of file ht.c.
References ht::dynamic, and ht_alloc().
ht_free()
int ht_free (ht * h)
frees a hash tables internal table.
Parameters
h hash table
Returns
an exit code
Definition at line 124 of file ht.c.
References ht::capacity, ht::len, and ht::table.
ht_is_empty()
int ht_is_empty (ht h)
check if hash table is empty
Parameters
h hash table
Returns
a boolean or -1 and set errno on error
Definition at line 161 of file ht.c.
References ht::len, and ht::table.
ht_is_full()
int ht_is_full (ht h)
check if hash table is full.
Parameters
h hash table
Returns
a boolean or -1 and set errno on error
Definition at line 143 of file ht.c.
References ht::capacity, ht::len, and ht::table.
ht_print()
void ht_print (ht h)
print out a hash tables data.
Parameters
h hash table
Returns
void
Definition at line 224 of file ht.c.
References ht::capacity, ht_print_key_type(), ht_print_val_type(), ht::key_type, ht::len, ht::table, and ht::val_type.
ht_search_i()
hte* ht_search_i (ht h, int key)
Definition at line 279 of file ht.c.
References hte::key::i, hte::key, ht::len, and ht::table.
ht_search_str()
hte* ht_search_str (ht h, char * key)
Definition at line 294 of file ht.c.
References hte::key, ht::len, hte::key::s, and ht::table.
ht_shrink()
int ht_shrink (ht * h)
shrink container to remove wasted space.
Parameters
h hash table ptr to shrink.
Returns
an exit code.
Definition at line 362 of file ht.c.
References ht::capacity, ht::len, and ht::table.
ht_typematch()
int ht_typematch (ht h, hte e)
check that a table and entry have the same key val scheme.
Parameters
h hash table
e hash table entry
Returns
a boolean for if the types match.
Definition at line 180 of file ht.c.
References hte::key_type, ht::key_type, hte::val_type, and ht::val_type.
hte_create_charp_charp_entry()
hte hte_create_charp_charp_entry (char * key, char * val)
Definition at line 62 of file ht.c.
References CHARP_VAL, INT_KEY, hte::key, hte::key_type, hte::next, hte::key::s, hte::val::s, hte::val, and hte::val_type.
hte_create_charp_flt_entry()
hte hte_create_charp_flt_entry (char * key, float val)
Definition at line 53 of file ht.c.
References CHARP_KEY, hte::val::f, FLT_VAL, hte::key, hte::key_type, hte::next, hte::key::s, hte::val, and hte::val_type.
hte_create_charp_int_entry()
hte hte_create_charp_int_entry (char * key, int val)
Definition at line 44 of file ht.c.
References CHARP_KEY, hte::val::i, INT_VAL, hte::key, hte::key_type, hte::next, hte::key::s, hte::val, and hte::val_type.
hte_create_charp_voidp_entry()
hte hte_create_charp_voidp_entry (char * key, void * val)
Definition at line 71 of file ht.c.
References INT_KEY, hte::key, hte::key_type, hte::next, hte::val::p, hte::key::s, hte::val, hte::val_type, and VOIDP_VAL.
hte_create_int_charp_entry()
hte hte_create_int_charp_entry (int key, char * val)
Definition at line 26 of file ht.c.
References CHARP_VAL, hte::key::i, INT_KEY, hte::key, hte::key_type, hte::next, hte::val::s, hte::val, and hte::val_type.
hte_create_int_flt_entry()
hte hte_create_int_flt_entry (int key, float val)
Definition at line 17 of file ht.c.
References hte::val::f, FLT_VAL, hte::key::i, INT_KEY, hte::key, hte::key_type, hte::next, hte::val, and hte::val_type.
hte_create_int_int_entry()
hte hte_create_int_int_entry (int key, int val)
Definition at line 8 of file ht.c.
References hte::key::i, hte::val::i, INT_KEY, INT_VAL, hte::key, hte::key_type, hte::next, hte::val, and hte::val_type.
hte_create_int_voidp_entry()
hte hte_create_int_voidp_entry (int key, void * val)
Definition at line 35 of file ht.c.
References hte::key::i, INT_KEY, hte::key, hte::key_type, hte::next, hte::val::p, hte::val, hte::val_type, and VOIDP_VAL.
hte_print()
void hte_print (hte e)
print out a single hash table entry.
Parameters
e hash table entry
Returns
void
Definition at line 243 of file ht.c.
References CHARP_VAL, hte::val::f, FLT_VAL, ht_print_key_type(), ht_print_val_type(), hte::key::i, hte::val::i, INT_KEY, INT_VAL, hte::key, hte::key_type, hte::next, hte::val::p, hte::key::s, hte::val::s, hte::val, and hte::val_type.
hte_print_chain()
void hte_print_chain (hte e)
Definition at line 267 of file ht.c.
References hte_print(), and hte::next.